viostream.settings:
  type: config_object
  label: 'Viostream settings'
  mapping:
    access_key:
      type: string
      label: 'Access Key'
    api_key:
      type: string
      label: 'API Key'

field.formatter.settings.viostream_video:
  type: mapping
  label: 'Viostream Video formatter settings'
  mapping:
    width:
      type: string
      label: 'Width'
    height:
      type: string
      label: 'Height'
    responsive:
      type: boolean
      label: 'Responsive'
    autoplay:
      type: boolean
      label: 'Autoplay'
    muted:
      type: boolean
      label: 'Muted'
    controls:
      type: boolean
      label: 'Show controls'

field.widget.settings.viostream_browser:
  type: mapping
  label: 'Viostream Browser widget settings'
